### ISSUE TITLE
Setting output IO for Ishi::Png has no effect

### ISSUE THREAD

**Issue by larilampen** [toddsundsted/ishi#6]
_Scenario_: I wish to use Ishi to output a chart into a PNG file.

_Sample code_:

```
require "ishi/png"

File.open("test.png", "w") do |file|
  ishi = Ishi::Png.new(file)
  ishi.plot([1, 2, 3, 4, 5], [1.0, 1.4, 1.9, 2.4, 2.6], "ko", title: "data")
  ishi.show
end
```

_Expected result_: A file called test.png is created, containing the chart.

_Actual result_: The PNG bitstream is written to the standard output. The file test.png is left empty.

_Underlying cause of the error_: The constructor in `Ishi::Png` calls the parent constructor, which sets `@@io`. However, due to the way class variables work in Crystal, it only sets the class variable `@@io` of class `Png` instead of `@@io` in `Term`, where class `Gnuplot` reads it from. Thus, whatever parameter is passed to `Png.new` has no effect on Ishi's behavior.

**Comment by toddsundsted** [comment]
@larilampen thanks! looking into this right now

**Comment by toddsundsted** [comment]
Fixed and released: https://github.com/toddsundsted/ishi/releases/tag/v0.7.1
