### ISSUE TITLE
Extra point plotted

### ISSUE THREAD

**Issue by jtanderson** [toddsundsted/ishi#8]
There is always an "extra" point getting plotted at approximately (1, 0.8). This occurs when the title is present (haven't figured out how to disable that without getting the '-' in its place), and can be seen in the examples on the main page.

**Comment by toddsundsted** [comment]
@jtanderson can you upload a picture or point out which one you are looking at?

**Comment by jtanderson** [comment]
I attached one of my own design, plotting points along the line y=x, and one can see the one extra point that is not along that line. The second attachment is from the README, where only 5 points are plotted but six are displayed.
![plot1](https://user-images.githubusercontent.com/889479/82604825-df24b500-9b82-11ea-9e28-e68e776bee49.png)
![plot2](https://user-images.githubusercontent.com/889479/82604827-dfbd4b80-9b82-11ea-97f5-9d0f7219214e.png)

**Comment by toddsundsted** [comment]
thanks! the extra point is part of the key. it is unfortunately placed in charts like these (up and to the right) and isn't visually highlighted in a helpful way. you can hide the key with `show_key false` which removes the extra point.

**Comment by jtanderson** [comment]
Interesting, I see! Is there a way to put the key/legend inside rectangle or adjust the positioning?

**Comment by toddsundsted** [comment]
not yet, but gnuplot supports it so it's possible.
